services:
  - type: web
    name: pii-phi
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --prefer-binary tokenizers && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: DEID_API_KEY
        sync: false
        optional: true

