services:
  - type: web
    name: pii-phi
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: DEID_API_KEY
        sync: false
        optional: true

